**Name - Arihant Gupta**
<br>
**Enrolment - E23CSEU0055**
<br>
**Batch - EB_02**
<br>
**Date - 16 Sep 2025**
<br>
**Lab - 13**

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

Load the Breast Cancer dataset from scikit-learn.

In [2]:
data = load_breast_cancer()
x = data.data
y = data.target

In [3]:
print(x)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


Split the dataset into training and testing sets.

In [4]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42,)

Standardize the data using StandardScaler to ensure better convergence of the neural
network.

In [5]:
scaler = StandardScaler()
x_train_std = scaler.fit_transform(x_train)
x_test_std = scaler.transform(x_test)

Choose at least 4-5 combinations of hyperparameters (hidden layers, alpha for
regularization, and learning rate)

Record the training and test accuracy for each experiment.

In [ ]:
experiments = [
    {"hidden_layer_sizes": (50,),      "L2-Regu": 1e-4, "Learning_Rate_GD": 0.001},
    {"hidden_layer_sizes": (100,),     "L2-Regu": 1e-4, "Learning_Rate_GD": 0.001},
    {"hidden_layer_sizes": (50, 50),   "L2-Regu": 1e-3, "Learning_Rate_GD": 0.001},
    {"hidden_layer_sizes": (100, 50),  "L2-Regu": 1e-4, "Learning_Rate_GD": 0.01},
    {"hidden_layer_sizes": (100, 100), "L2-Regu": 1e-2, "Learning_Rate_GD": 0.001},
    {"hidden_layer_sizes": (64, 32, 16), "L2-Regu": 1e-4, "Learning_Rate_GD": 0.001},
]

results = []

for i, params in enumerate(experiments, 1):
    clf = MLPClassifier(
        hidden_layer_sizes=params["hidden_layer_sizes"],
        alpha=params["alpha"],
        learning_rate_init=params["Learning_Rate_GD"],
        max_iter=2000,
        random_state=42,
        early_stopping=True,
    )
    clf.fit(x_train_std, y_train)
    y_pred_train = clf.predict(x_train_std)
    y_pred_test = clf.predict(x_test_std)
    train_acc = accuracy_score(y_train, y_pred_train)
    test_acc = accuracy_score(y_test, y_pred_test)
    results.append({
        "exp_id": i,
        **params,
        "train_accuracy": train_acc,
        "test_accuracy": test_acc,
        "n_iter_": getattr(clf, 'n_iter_', None),
        "best_validation_score_": getattr(clf, 'best_validation_score_', None),
    })

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by=["test_accuracy", "train_accuracy"], ascending=False).reset_index(drop=True)

print(results_df)

   exp_id hidden_layer_sizes   alpha  learning_rate_init  train_accuracy  \
0       4          (100, 50)  0.0001               0.010        0.940659   
1       2             (100,)  0.0001               0.001        0.923077   
2       5         (100, 100)  0.0100               0.001        0.980220   
3       1              (50,)  0.0001               0.001        0.964835   
4       3           (50, 50)  0.0010               0.001        0.909890   
5       6       (64, 32, 16)  0.0001               0.001        0.934066   

   test_accuracy  n_iter_  best_validation_score_  
0       0.982456       12                1.000000  
1       0.982456       13                0.934783  
2       0.973684       30                0.978261  
3       0.964912       26                0.978261  
4       0.956140       14                0.891304  
5       0.921053       20                0.956522  


Train the model with MLPClassifier for each combination.

In [8]:
param_grid = {
    'hidden_layer_sizes': [(50,), (100,), (50,50), (100,50), (64,32,16)],
    'alpha': [1e-4, 1e-3, 1e-2],
    'learning_rate_init': [0.001, 0.01]
}

grid = GridSearchCV(
    MLPClassifier(max_iter=2000, random_state=42, early_stopping=True),
    param_grid, cv=5, scoring='accuracy'
)
grid.fit(x_train_std, y_train)

print("Best params:", grid.best_params_)
print("Train score:", grid.score(x_train_std, y_train))
print("Test score:", grid.score(x_test_std, y_test))

Best params: {'alpha': 0.0001, 'hidden_layer_sizes': (100, 50), 'learning_rate_init': 0.01}
Train score: 0.9406593406593406
Test score: 0.9824561403508771


Analyze results and write a short conclusion about the impact of hyperparameter choices.

I trained the model with two approaches, first to calculate the accuracy on each combination of the hyperparameters.

<br>

The second approach was using the GridSearchCV technique to automatically map the hyperparameter combinations and test each one.

<br>

The best hyperparameters and the best accuracy in both scenarios MATCHED, hence we can that the final Hyperparameter in just above code block is the best.